version: "2.0"

services:
  spacedeck:
    build: .
    container_name: spacedeck
    ports:
      - "9666:9666"
    volumes:
      - ./tmp/storage:/app/storage
      - ./tmp/database.sqlite:/app/database.sqlite

